[package]
name = "tack-it-on"
version = "0.1.0"
authors = ["Chris Wells Wood <cwwoodesq@gmail.com>"]

[dependencies]
clap = "2"
glob = "0.2.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
text_io = "0.1.6"
